theme: jekyll-theme-minimal
title: Ziqi Gao (Roy)
description: Ph.D. Student @ UW CSE
logo: img/ziqigao.jpg
Google Scholar: https://scholar.google.com/citations?view_op=list_works&hl=en&hl=en&user=YMw0lS4AAAAJ
X (Twitter): https://x.com/ziqigaothu
# description: Master’s student @ UW CSE RAIVN Lab and Tsinghua Pervasive HCI Lab
