theme: jekyll-theme-minimal
title: Ziqi Gao (Roy)
description: PYI @ AI2 PRIOR
logo: img/ziqigao.jpg
Google Scholar: https://scholar.google.com/citations?user=DPBvFloAAAAJ&hl=en
# description: Master’s student @ UW CSE RAIVN Lab and Tsinghua Pervasive HCI Lab
